### ISSUE TITLE
<style> element used for calculation isn't being removed

### ISSUE THREAD

**Issue by Snugug** [GoogleChromeLabs/css-paint-polyfill#12]
The inline <style> element that I presume is used for calculating what should be painted isn't being properly removed from the DOM in both Firefox and Safari, leading to cascade bugs in those browsers. Based on an offline discussion, it appears that the expected result is that they're removed, but given that they're not, it may be worthwhile to swap them over to an invalid media query instead.

**Comment by developit** [comment]
Fixed in [2.0.0](https://github.com/GoogleChromeLabs/css-paint-polyfill/releases/tag/2.0.0).
