### ISSUE TITLE
Demo doesn't work

### ISSUE THREAD

**Issue by jespertheend** [GoogleChromeLabs/css-paint-polyfill#22]
When I run the steps at the bottom of `readme.md` and go to http://localhost:5000/demo/, the ripple effect doesn't work for any browser except for Chrome.
https://googlechromelabs.github.io/css-paint-polyfill/ still seems to be working in Safari and FireFox though.

**Comment by ntoniazzi** [comment]
I checked the different releases on Firefox 89. 3.1.0 works well, but not 3.1.1.
The change in `maybeUpdateElement()` broke it:
https://github.com/GoogleChromeLabs/css-paint-polyfill/commit/976f0f8d50c3506f5b7009350dc79bc97db346f2#diff-bfe9874d239014961b1ae4e89875a6155667db834a410aaaa2ebe3cf89820556R489-R490

**Comment by jespertheend** [comment]
Ah that explains why https://googlechromelabs.github.io/css-paint-polyfill/ is still working on Firefox. I guess it's using an old version.

**Comment by developit** [comment]
Fix released as [3.3.0](https://github.com/GoogleChromeLabs/css-paint-polyfill/releases/tag/3.3.0) - thanks!
