### ISSUE TITLE
Polyfill seemingly not working.

### ISSUE THREAD

**Issue by maxall41** [GoogleChromeLabs/css-paint-polyfill#30]
For some reason i can't get this polyfill to work for me. I tried loading the demo in Safari and Firefox but nothing happens but it works just fine in a Chrome version that supports the paint API natively. Am i doing something wrong here? It seems like the issue is with the CSS `background-image: paint(worklet)` line because the browser does not understand the paint part of that line it's highlighted with a yellow warning sign in both Safari And Firefox. Is there some separate polyfill i have to use for the non-native supporting browsers to understand the CSS? One of the other weird things about this is pulling up the `https://googlechromelabs.github.io/css-paint-polyfill/` page in Firefox and Safari works fine but downloading the demo and hosting it and then viewing it in Safari and Firefox does not work. And when pressing the button using the goglechromelabs.github.io demo it shows the same yellow warning sign. In addition to the demo not working my own site which uses the polyfill doesn't work either `https://www.maxc.codes/` in Safari or Firefox and it doesn't throw any errors and registers the worklet just fine but the browser cant understand the css.

**Comment by SeanCox** [comment]
@maxall41 when you register your worklet are you using the same name?
the register should look something like this: `registerPaint('customBackgroundName', BackgroundPainter)`
and the CSS would look like:  `backgroundImage: paint(customBackgroundName)`
If you have repo or code example I could take more in-depth look for you if you want.

**Comment by maxall41** [comment]
@SeanCox Yeah. Here is the source code https://github.com/maxall41/maxall41.github.io
On branch `newv2`

**Comment by developit** [comment]
@maxall41 your conditional wrapping the polyfill import is reversed:

```diff
-if ('paintWorklet' in CSS) {
+if (!('paintWorklet' in CSS)) {
```

**Comment by maxall41** [comment]
@developit Thanks!
