### ISSUE TITLE
Only the first paint is picked up

### ISSUE THREAD

**Issue by nbremer** [GoogleChromeLabs/css-paint-polyfill#4]
Hi,

I noticed that only the first `paint(something)` was picked up out of my css, where I had created more than one different paint class. Adding a `g` to the regex from `escapePaintRules` seems to fix this issue for me:

```javascript
function escapePaintRules(css) {
	return css.replace(/(;|,|\b)paint\s*\(\s*(['"]?)(.+?)\2\s*\)(;|,|!|\b)/g, '$1url(data:image/paint-$3,=)$4');
}
```

**Comment by developit** [comment]
Nice catch!
