### ISSUE TITLE
Functions called before the paint is registered

### ISSUE THREAD

**Issue by nbremer** [GoogleChromeLabs/css-paint-polyfill#7]
This one is a bit vague, I don't know exactly why it's sometimes going wrong, but I have found a "hack" to make sure it doesn't happen anymore

I've found that, especially in Safari, that maybe 1 in 4 or 5 times the following lines in the `update()` function are run before the `registerPaint` is done/has been performed all the way at the bottom in the `addModule(url)` 

```javascript
if (context.toProcess.length>0) {
	processItem(context.toProcess.join(', '));
}
```

Although this isn't where the "real" issue lies, that comes later in the chain of functions that is called, and once the program ends up in the `updateElement` function the following returns `undefined`

```javascript
let painter = getPainter(painterName);
```

OR, the paint seems not picked up at all, and nothing appears on my page (of the "paint" I mean, nothing is drawn from my paint worklets)

My "fix" is to wrap the `processItem` line in a `setTimeout`:

```javascript
setTimeout(() => {
	if (context.toProcess.length>0) {
		processItem(context.toProcess.join(', '));
	}
}, 300)
```

Not pretty, but it seems to do the trick for me. I'm just wondering what the better solution would be

**Comment by developit** [comment]
I *think* this should be gone in 2.0.0 as a result of the CSS parsing fix.

**Comment by developit** [comment]
3.0.0 (`npm i css-paint-polyfill@next`) no longer relies on timing, and correctly triggers repainting of affected elements after a paint worklet has been initialized.
